### PR TITLE
Adjust job stores for ptb v20.4

### PR DESCRIPTION
**Pull request by Bibo-Joshi**
Specifically to https://github.com/python-telegram-bot/python-telegram-bot/pull/3695

### CODE REVIEW

**Comment by Bibo-Joshi** [comment]
@Giulianini @Holmes555 could one of you maybe double check that this works for you locally with PTB v20.4?

**Comment by Giulianini** [comment]
Using it with my actual bot and no problems whatsoever

**Comment by Bibo-Joshi** [comment]
To clarify: I'm asking if you can verify if the changes proposed by this PR work. v20.4 removed the (protected!) classmethod `Job._from_aps_job` which is currently used by `PTBStoreAdapter` so I expect that the job stores will fail in many cases when using them on v20.4.

**Comment by Giulianini** [comment]
> To clarify: I'm asking if you can verify if the changes proposed by this PR work. v20.4 removed the (protected!) classmethod `Job._from_aps_job` which is currently used by `PTBStoreAdapter` so I expect that the job stores will fail in many cases when using them on v20.4.

It was not working, so I debugged it. Found out that now it's only passing job_queue and not the all application object
Fix with `self.application.job_queue,` inestead of `self.application`

**Comment by Bibo-Joshi** [comment]
Thanks for the finding! Should be fixed now.

**Pull request merged**
